version: '3.4'

services:
  mijnstemback:
    image: ${DOCKER_REGISTRY-}mijnstemback
    build:
      context: .
      dockerfile: MijnstemBack/Dockerfile
    ports:
      - 8080:8080


  mijnstemfront:
    container_name: mijnstemfront
    build:
      context: ./mijnstemfront
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start


  mijnstemadminfront:
    container_name: mijnstemadminfront
    build:
      context: ./mijnstemadminfront
      dockerfile: ./Dockerfile
    ports:
      - 3030:3030
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start