version: '3.4'

services:
  mijnstemback:
    build:
      context: ./Mijn Stem Back
      dockerfile: ./Dockerfile
    ports:
       - '4000:4000'
    command: npm start

  mijnstemfront:
    container_name: mijnstemfront
    build:
      context: ./mijnstemfront
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start